#!/usr/bin/env bash

declare APPFOLDER
APPFOLDER=$( readlink -f "$0" )
APPFOLDER="${APPFOLDER%/*}"
source "$APPFOLDER"/sources/include
source "$APPFOLDER"/man_seeker.sh
source "$APPFOLDER"/man_heads.sh
source "$APPFOLDER"/man_pager.sh


# Starts the user interface
#
# Args:
#  (string):  path to man page source
#  (string):  name of command for which the man page was requested
#  (string):  section number of the manual
iman_open()
{
    local io_path="$1"
    local io_command="$2"
    local io_section="$3"

    # Various arrays to be filled by reading the source code,
    # and used by the pager to deliver the user experience
    local -a io_hotkeys=()   # simple array of keys matched to heads
    local -a io_heads        # will be lui_list of heads for the lui_list interaction
    local -a io_lines        # uncompressed source file for showing subsections

    local -i io_selection

    if man_heads_read_headers "io_heads" "io_hotkeys" "io_lines" "$io_path"; then
        hide_cursor
        io_selection=0
        mp_start_pager "io_selection" "io_heads" "io_lines" "$io_command" "$io_section" "io_hotkeys"
        show_cursor
    fi
}

#############################################
########## SCRIPT EXECUTION BEGINS ##########
#############################################

if [ "$#" -gt 0 ]; then
    declare man_path=""
    declare man_command=""
    declare man_section=""
    if man_seeker_find_man_file "man_path" "man_command" "man_section" "$@"; then
        reset_screen
        iman_open "$man_path" "$man_command" "$man_section"
    else
        echo "No manual entry for $man_command in section $man_section."
    fi
else
    echo "No man page to seek"
fi
